### ISSUE TITLE
Sentence Transformersのtokenizerの設定追加

### ISSUE THREAD

**Issue by akiFQC** [sbintuitions/JMTEB#31]
現状では、Sentence Transformerのインスタンス化の際にトークナイザーの設定をargparseから追加することができない。

sbintuitions/sarashina2-7b などのモデルでは、`tokenizer_fast=False`を指定する必要があるので、`SentenceBertEmbedder`の__init__の変数にトークナイザー設定用のdictを追加できると嬉しい。

**Comment by lsz05** [comment]
#30 でcomplete
