### ISSUE TITLE
複数GPUで`SentenceBertEmbedder` のencodeを行いたい

### ISSUE THREAD

**Issue by akiFQC** [sbintuitions/JMTEB#36]
現状の実装だと、複数GPU環境であっても1つのGPUしか使えないように見えるので、複数のGPUを使ってテキスト埋め込みをできるようにしたい。

実装方法としては、下記が参考になると想定される。
https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/computing-embeddings/computing_embeddings_multi_gpu.py

**Comment by lsz05** [comment]
@akiFQC #38 で対応しましたので本issueクローズとさせていただいてもよろしいでしょうか
