### ISSUE TITLE
ベンチマークの引数などをyamlかjson形式で結果を保存するディレクトリに保存する

### ISSUE THREAD

**Issue by akiFQC** [sbintuitions/JMTEB#46]
## 現状の問題と要望
- jmtebでベンチマークをするときの設定は結果の出力ディレクトに保存されない
- 実験の再現性という観点で、実験の設定をyamlかjson形式で保存して、再利用・再参照できるようにしたい

**Comment by lsz05** [comment]
#84 で本issueクローズします
