### ISSUE TITLE
[EVAL REQUEST] Ruri Series

### ISSUE THREAD

**Issue by akiFQC** [sbintuitions/JMTEB#69]
## モデルの基本情報
**name**: cl-nagoya/ruri-large, cl-nagoya/ruri-base, cl-nagoya/ruri-small
**type**:  BERT
**size**: 
**lang**: ja 

## モデル詳細

- https://huggingface.co/cl-nagoya/ruri-large
- https://huggingface.co/cl-nagoya/ruri-base
- https://huggingface.co/cl-nagoya/ruri-small

## seen/unseen申告
JMTEBの評価データセットの中，training splitをモデル学習に使用した，またはvalidation setとして，ハイパラチューニングやearly stoppingに使用したデータセット名をチェックしてください。
* Classification
  * [ ] Amazon Review Classification
  * [ ] Amazon Counterfactual Classification
  * [ ] Massive Intent Classification
  * [ ] Massive Scenario Classification
* Clustering
  * [ ] Livedoor News
  * [ ] MewsC-16-ja
* STS
  * [ ] JSTS
  * [ ] JSICK
* Pair Classification
  * [ ] PAWS-X-ja
* Retrieval
  * [ ] JAQKET
  * [ ] Mr.TyDi-ja
  * [ ] JaGovFaqs-22k
  * [ ] NLP Journal title-abs
  * [ ] NLP Journal title-intro
  * [ ] NLP Journal abs-intro
* Reranking
  * [ ] Esci
* [x] 申告しません

**Comment by lsz05** [comment]
#70
