### ISSUE TITLE
[Question] What does `relevance_scores` in ESCI reranking dataset represent?

### ISSUE THREAD

**Issue by omihub777** [sbintuitions/JMTEB#78]
Thank you for your great work. I have a quick question regarding `relevance_scores` in ESCI. In [your version of ESCI dataset](https://huggingface.co/datasets/sbintuitions/JMTEB#esci), the `relevance_scores` takes one of the values from 0 to 3. What does each value correspond to the original labels (i.e. Exact / Substitute / Complement / Irrelevant)? My guess would be `0: Irrelevant`, `1: Complement`, `2: Substitute`, `3: Exact`, but want your confirmation. Thanks.

**Comment by lsz05** [comment]
Hello, thank you for the issue!

Your guess is right. We convert labels to integer with the following dictionary: https://huggingface.co/datasets/sbintuitions/JMTEB/blob/7e8ad98b751ab42c572ceb4e7723a2885a3d2cfe/reranking.py#L24

**Comment by omihub777** [comment]
Thanks!
