### ISSUE TITLE
[EVAL REQUEST] sbintuitions/sarashina-embedding-v1-1b

### ISSUE THREAD

**Issue by akiFQC** [sbintuitions/JMTEB#88]
## モデルの基本情報
**name**: https://huggingface.co/sbintuitions/sarashina-embedding-v1-1b
**type**: LLaMA
**size**: 1.2B
**lang**: ja 

## モデル詳細

https://huggingface.co/sbintuitions/sarashina-embedding-v1-1b

## seen/unseen申告
JMTEBの評価データセットの中，training splitをモデル学習に使用した，またはvalidation setとして，ハイパラチューニングやearly stoppingに使用したデータセット名をチェックしてください。
* Classification
  * [ ] Amazon Review Classification
  * [ ] Amazon Counterfactual Classification
  * [ ] Massive Intent Classification
  * [ ] Massive Scenario Classification
* Clustering
  * [ ] Livedoor News
  * [ ] MewsC-16-ja
* STS
  * [ ] JSTS
  * [ ] JSICK
* Pair Classification
  * [ ] PAWS-X-ja
* Retrieval
  * [ ] JAQKET
  * [x] Mr.TyDi-ja
  * [ ] JaGovFaqs-22k
  * [ ] NLP Journal title-abs
  * [ ] NLP Journal title-intro
  * [ ] NLP Journal abs-intro
* Reranking
  * [ ] Esci
* [ ] 申告しません

**Comment by lsz05** [comment]
#89
